linestorm_blog_admin_module_media:
    pattern:  /
    defaults: { _controller: LineStormBlogBundle:Admin/Media:list }


linestorm_blog_admin_module_media_api:
  type:         rest
  prefix:       /api
  resource:     "api.yml"


linestorm_blog_admin_module_media_create:
    pattern:  /new
    defaults: { _controller: LineStormBlogBundle:Admin/Media:new }

linestorm_blog_admin_module_media_view:
    pattern:  /{id}
    defaults: { _controller: LineStormBlogBundle:Admin/Media:view }
    requirements:
       id: \d+

linestorm_blog_admin_module_media_edit:
    pattern:  /{id}/edit
    defaults: { _controller: LineStormBlogBundle:Admin/Media:edit }
    requirements:
       id: \d+

linestorm_blog_media_upload_edit:
    path: /{id}/upload
    defaults: { _controller: "LineStormBlogBundle:Admin/Media:uploadEdit" }
    requirements:
       id: \d+

linestorm_blog_media_upload:
    path: /upload
    defaults: { _controller: "LineStormBlogBundle:Admin/Media:upload" }

