linestorm_blog_routes:
  resource: .
  type:       linestorm_blog

linestorm_blog_api:
  prefix:       /api
  resource:     'routing/api.yml'

linestorm_blog_admin:
  prefix:       /admin
  resource:     'routing/admin.yml'
