linestorm_blog_admin_module_media_api_controller:
    type:     rest
    resource: LineStorm\BlogBundle\Controller\Admin\Api\MediaController
    name_prefix:  linestorm_blog_admin_module_media_api_
