linestorm_blog_admin_post:
    path:     /
    defaults: { _controller: "LineStormBlogBundle:AdminPost:index" }

linestorm_blog_admin_post_show:
    path:     /{id}/show
    defaults: { _controller: "LineStormBlogBundle:AdminPost:show" }

linestorm_blog_admin_post_new:
    path:     /new
    defaults: { _controller: "LineStormBlogBundle:AdminPost:new" }

linestorm_blog_admin_post_create:
    path:     /create
    defaults: { _controller: "LineStormBlogBundle:AdminPost:create" }
    requirements: { _method: post }

linestorm_blog_admin_post_edit:
    path:     /{id}/edit
    defaults: { _controller: "LineStormBlogBundle:AdminPost:edit" }
    requirements:
        id: \d+

linestorm_blog_admin_post_update:
    path:     /{id}/update
    defaults: { _controller: "LineStormBlogBundle:AdminPost:update" }
    requirements: { _method: post|put }

linestorm_blog_admin_post_delete:
    path:     /{id}/delete
    defaults: { _controller: "LineStormBlogBundle:AdminPost:delete" }
    requirements: { _method: post|delete }
