linestorm_blog_api_post:
    type:     rest
    resource: LineStorm\BlogBundle\Controller\Api\PostController
    name_prefix:  linestorm_blog_api_

linestorm_blog_api_tag:
    type:     rest
    resource: LineStorm\BlogBundle\Controller\Api\TagController
    name_prefix:  linestorm_blog_api_

linestorm_blog_api_category:
    type:     rest
    resource: LineStorm\BlogBundle\Controller\Api\CategoryController
    name_prefix:  linestorm_blog_api_
