linestorm_blog_admin_module_post_list:
    pattern:  /
    defaults: { _controller: LineStormBlogBundle:Admin/Post:list }

linestorm_blog_admin_module_post_edit:
    pattern:  /{id}/edit
    defaults: { _controller: LineStormBlogBundle:Admin/Post:edit }
    requirements:
       id: \d+

linestorm_blog_admin_module_post_view:
    pattern:  /{id}
    defaults: { _controller: LineStormBlogBundle:Admin/Post:view }
    requirements:
       id: \d+

linestorm_blog_admin_module_post_create:
    pattern:  /new
    defaults: { _controller: LineStormBlogBundle:Admin/Post:new }

linestorm_blog_admin_module_post_api_post:
  type:         rest
  prefix:       /api
  resource:     "api.yml"
