parameters:
  linestorm.cms.routing_loader.class:          LineStorm\CmsBundle\Router\CmsLoader
  linestorm.cms.admin.routing_loader.class:    LineStorm\CmsBundle\Router\CmsAdminLoader

  linestorm.cms.model_manager.class:           LineStorm\CmsBundle\Model\ModelManager
  linestorm.cms.module_manager.class:          LineStorm\CmsBundle\Module\ModuleManager

services:

  linestorm.cms.routing_loader:
    class: %linestorm.cms.routing_loader.class%
    arguments: [@linestorm.cms.module_manager]
    tags:
      - { name: routing.loader }

  linestorm.cms.admin.routing_loader:
    class: %linestorm.cms.admin.routing_loader.class%
    arguments: [@linestorm.cms.module_manager]
    tags:
      - { name: routing.loader }

  linestorm.cms.module_manager:
    class: %linestorm.cms.module_manager.class%

  linestorm.cms.model_manager:
    class: %linestorm.cms.model_manager.class%
    calls:
      - [ setMappings, [%linestorm_cms.entity_config%] ]
      - [ setEntityManager, [@doctrine, %linestorm_cms.entity_manager%] ]

  #
  # TWIG ADMIN
  linestorm.cms.twig.cms_extension:
    class: LineStorm\CmsBundle\Twig\CmsAdminExtension
    arguments: [ @linestorm.cms.module_manager, @linestorm.cms.asset_factory ]
    tags:
      - { name: twig.extension }

  linestorm.cms.asset_factory:
    class: Assetic\Factory\AssetFactory
    arguments: [%assetic.read_from%, %assetic.debug%]
    calls:
      - [ setAssetManager, [@linestorm.cms.asset_manager]]
      - [ setFilterManager, [@assetic.filter_manager]]

  linestorm.cms.asset_manager:
    class: Assetic\Factory\LazyAssetManager
    arguments: [@linestorm.cms.asset_factory]
